### ISSUE TITLE
How to use workflow with hosted kutt.it using custom domain?

### ISSUE THREAD

**Issue by jonpurdy** [thedevs-network/alfred-kutt#2]
Title says it all. Is there an option for using the custom domain I've added to kutt.it?

**Comment by vtmocanu** [comment]
Hey, have you found any workarounds to do this?

**Comment by itsbrex** [comment]
Trying to figure this out as well.

**Comment by dewittn** [comment]
In the workflows tab, you have to right-click on the Kutt workflow and select `Open in Finder`. 

<img width="190" alt="Screen Shot 2022-01-19 at 11 27 18 AM" src="https://user-images.githubusercontent.com/10439/150173315-574f2dcf-6c18-4cdd-959b-6e51a33aad9a.png">

From there you can edit `index.js` and replace the `url: "https://kutt.it/api/url/submit"` with your own URL.

<img width="731" alt="Screen Shot 2022-01-19 at 11 27 55 AM" src="https://user-images.githubusercontent.com/10439/150173352-954aa500-54bd-47c7-b41b-a6ea2e5aea45.png">
